name: Build Flet APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Flutter version
      run: flutter --version

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Install Android SDK
      run: |
        yes | sdkmanager --update
        sdkmanager "platform-tools" "platforms;android-30"

    - name: Check Flutter doctor
      run: flutter doctor -v

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
